//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maquetteABI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Contacts = new HashSet<Contacts>();
        }
    
        public int Numero_Client { get; set; }
        public string Raison_Social { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string Domaine { get; set; }
        public string Type { get; set; }
        public string Ville { get; set; }
        public string Code_postal { get; set; }
        public string Nature { get; set; }
        public decimal Chiffre_d_affaire { get; set; }
        public string Effectif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacts> Contacts { get; set; }
    }
}
